services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=2012
      - POSTGRES_DB=Marketplace
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d Marketplace"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - app-network

  # ОСНОВНОЕ приложение (shop_project)
  app:
    build:
      context: .
      dockerfile: shop/Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/Marketplace
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 2012
      SPRING_FLYWAY_URL: jdbc:postgresql://postgres:5432/Marketplace
      SPRING_FLYWAY_USER: user
      SPRING_FLYWAY_PASSWORD: 2012
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network

  # АУДИТ сервис
  audit:
    build:
      context: .
      dockerfile: audit/Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/Marketplace
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 2012
      SPRING_FLYWAY_URL: jdbc:postgresql://postgres:5432/Marketplace
      SPRING_FLYWAY_USER: user
      SPRING_FLYWAY_PASSWORD: 2012
    deploy:
      replicas: 5
    # ports:
    #   - "8081:8081" # Отключаем проброс порта, чтобы не было конфликта при масштабировании
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network

volumes:
  pgdata:
  rabbitmq_data:

networks:
  app-network:
    driver: bridge