spring:
  config:
    activate:
      on-profile: prod

  application:
    name: shop_project
  datasource:
    url: jdbc:postgresql://localhost:5432/Marketplace
    username: postgres
    password: 2012
  flyway:
    url: jdbc:postgresql://localhost:5432/Marketplace
    user: postgres
    password: 2012
    locations: filesystem:db/migration
    enabled: true
    baseline-on-migrate: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    exchange: oms
    exchangeMappings:
      - queue: oms.order.created
        routingKeyPattern: order.created
        deadLetter:
          dlx: oms.order.dlx
          routingKey: order.created
      - queue: oms.order.status.changed
        routingKeyPattern: order.status.changed
        deadLetter:
          dlx: oms.order.dlx
          routingKey: order.status.changed
      - queue: public.oms.order.created
        routingKeyPattern: order.created
      - queue: public.oms.order.status.changed
        routingKeyPattern: order.status.changed
      - queue: oms.logs
        routingKeyPattern: order.*
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 10
          initial-interval: 3000
          multiplier: 1.5
