spring:
  config:
    activate:
      on-profile: prod


  application:
    name: shop_project
  datasource:
    url: jdbc:postgresql://localhost:15432/Marketplace
    username: postgres
    password: 2012
  flyway:
    url: jdbc:postgresql://localhost:15432/Marketplace
    user: postgres
    password: 2012
    locations: classpath:db/migration
    enabled: true


